use std::path::PathBuf;
use std::time::Duration;

use clap::{Parser, ValueEnum};

// constants (used as defaults)
#[allow(dead_code)]
pub const SEMAPHORE_LIMIT: usize = 500;
pub const LOGGING_INTERVAL: usize = 5;
pub const URL_PROCESSING_TIMEOUT: Duration = Duration::from_secs(10);
pub const DB_PATH: &str = "./url_checker.db";

// URL validation
pub const URL_SCHEME_PATTERN: &str = r"^https?://";

// Security header names
pub const HEADER_CONTENT_SECURITY_POLICY: &str = "Content-Security-Policy";
pub const HEADER_STRICT_TRANSPORT_SECURITY: &str = "Strict-Transport-Security";
pub const HEADER_X_CONTENT_TYPE_OPTIONS: &str = "X-Content-Type-Options";
pub const HEADER_X_FRAME_OPTIONS: &str = "X-Frame-Options";
pub const HEADER_X_XSS_PROTECTION: &str = "X-XSS-Protection";
pub const HEADER_REFERRER_POLICY: &str = "Referrer-Policy";
pub const HEADER_PERMISSIONS_POLICY: &str = "Permissions-Policy";

// Response and body size limits
/// Maximum response body size in bytes (2MB)
/// Responses larger than this are skipped to prevent memory exhaustion
pub const MAX_RESPONSE_BODY_SIZE: usize = 2 * 1024 * 1024;

// Redirect handling
/// Maximum number of redirect hops to follow
/// Prevents infinite redirect loops and excessive request chains
pub const MAX_REDIRECT_HOPS: usize = 10;

// Error rate limiting
/// Divisor used to calculate backoff duration from error rate
/// Higher values result in shorter backoff times
pub const ERROR_RATE_BACKOFF_DIVISOR: f64 = 5.0;

// Retry strategy
/// Initial delay in milliseconds before first retry
pub const RETRY_INITIAL_DELAY_MS: u64 = 1000;
/// Factor by which retry delay is multiplied on each attempt
pub const RETRY_FACTOR: u64 = 2;
/// Maximum delay between retries in seconds
pub const RETRY_MAX_DELAY_SECS: u64 = 20;

/// Logging level for the application.
///
/// Controls the verbosity of log output, from most restrictive (Error) to most
/// verbose (Trace). Used with the `--log-level` CLI option.
#[derive(Clone, Debug, ValueEnum)]
pub enum LogLevel {
    Error,
    Warn,
    Info,
    Debug,
    Trace,
}

impl From<LogLevel> for log::LevelFilter {
    fn from(l: LogLevel) -> Self {
        match l {
            LogLevel::Error => log::LevelFilter::Error,
            LogLevel::Warn => log::LevelFilter::Warn,
            LogLevel::Info => log::LevelFilter::Info,
            LogLevel::Debug => log::LevelFilter::Debug,
            LogLevel::Trace => log::LevelFilter::Trace,
        }
    }
}

/// Log output format.
///
/// Controls how log messages are formatted:
/// - `Plain`: Human-readable format with colors (default)
/// - `Json`: Structured JSON format for machine parsing
#[derive(Clone, Debug, ValueEnum)]
pub enum LogFormat {
    Plain,
    Json,
}

/// Command-line options and configuration.
///
/// This struct is automatically generated by `clap` from the field attributes.
/// All options have sensible defaults and can be overridden via command-line flags.
///
/// # Examples
///
/// ```bash
/// # Basic usage
/// domain_status urls.txt
///
/// # With custom concurrency and timeout
/// domain_status urls.txt --max-concurrency 100 --timeout-seconds 5
///
/// # With custom database path
/// domain_status urls.txt --db-path ./custom.db
/// ```
#[derive(Debug, Parser)]
#[command(
    name = "domain_status",
    about = "Checks a list of URLs for their status and redirection."
)]
pub struct Opt {
    /// File to read
    #[arg(value_parser)]
    pub file: PathBuf,

    /// Error rate threshold
    #[arg(long, default_value = "60.0")]
    pub error_rate: f64,

    /// Log level: error|warn|info|debug|trace
    #[arg(long, value_enum, default_value_t = LogLevel::Info)]
    pub log_level: LogLevel,

    /// Log format: plain|json
    #[arg(long, value_enum, default_value_t = LogFormat::Plain)]
    pub log_format: LogFormat,

    /// Database path (SQLite file)
    #[arg(long, value_parser, default_value = "./url_checker.db")]
    pub db_path: PathBuf,

    /// Maximum concurrent requests
    #[arg(long, default_value_t = 500)]
    pub max_concurrency: usize,

    /// Per-request timeout in seconds
    #[arg(long, default_value_t = 10)]
    pub timeout_seconds: u64,

    /// HTTP User-Agent header value
    #[arg(
        long,
        default_value = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
    )]
    pub user_agent: String,

    /// Requests per second rate limit (0 disables limiting)
    #[arg(long, default_value_t = 0)]
    pub rate_limit_rps: u32,

    /// Rate limit burst capacity (tokens), defaults to max concurrency if 0
    #[arg(long, default_value_t = 0)]
    pub rate_burst: usize,
}
